import{a as y,S as B,i}from"./assets/vendor-CucEYOFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const n of r.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();const g="https://pixabay.com/api",M="54685682-80977b0b5ca1319a1902ced87",O=15;y.defaults.baseURL=g;async function h(o,t){return(await y({url:g,method:"get",params:{key:M,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:O}})).data}const p=document.querySelector(".gallery"),b=document.querySelector(".loader"),d=document.querySelector(".load-more-btn"),x=new B(".gallery a",{captionsData:"alt",captionDelay:250});function L(o){const t=o.map(({webformatURL:s,largeImageURL:a,tags:e,likes:r,views:n,comments:P,downloads:$})=>`
    <li class="gallery-item">
      <a class="gallery-link" href="${a}">
        <img class="gallery-image" src="${s}" alt="${e}" />
      </a>
      <div class="info">
        <p class="info-item"><b>Likes</b><br/>${r}</p>
        <p class="info-item"><b>Views</b><br/>${n}</p>
        <p class="info-item"><b>Comments</b><br/>${P}</p>
        <p class="info-item"><b>Downloads</b><br/>${$}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),x.refresh()}function E(){p.innerHTML=""}function w(){b.classList.remove("is-hidden")}function S(){b.classList.add("is-hidden")}function v(){d&&d.classList.remove("is-hidden")}function u(){d&&d.classList.add("is-hidden")}const m=document.querySelector(".form"),f=document.querySelector(".load-more-btn");let l="",c=1;const q=15;m&&m.addEventListener("submit",async o=>{o.preventDefault();const t=o.currentTarget;if(l=t.elements["search-text"].value.trim(),l===""){i.warning({title:"Warning",message:"Please enter a search query!"});return}c=1,E(),u(),w();try{const s=await h(l,c);if(s.hits.length===0){i.error({message:"Sorry, there are no images matching your search query."});return}L(s.hits),s.totalHits>q&&v()}catch(s){console.error(s),i.error({message:"Something went wrong."})}finally{S(),t.reset()}});f&&f.addEventListener("click",async()=>{c+=1,u(),w();try{const o=await h(l,c);L(o.hits);const t=document.querySelector(".gallery-item");if(t){const{height:a}=t.getBoundingClientRect();window.scrollBy({top:a*2,behavior:"smooth"})}const s=Math.ceil(o.totalHits/q);c>=s?(u(),i.info({message:"We're sorry, but you've reached the end of search results."})):v()}catch(o){console.error(o),i.error({message:"Failed to load more images."})}finally{S()}});
//# sourceMappingURL=index.js.map
